/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCadastrarRouteImport } from './routes/admin.cadastrar'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppImpactoRouteImport } from './routes/app.impacto'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppResgatesRouteImport } from './routes/app.resgates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrarRoute = AdminCadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppImpactoRoute = AppImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppResgatesRoute = AppResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/cadastrar': typeof AdminCadastrarRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/app/impacto': typeof AppImpactoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/resgates': typeof AppResgatesRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/cadastrar': typeof AdminCadastrarRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/app/impacto': typeof AppImpactoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/resgates': typeof AppResgatesRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/cadastrar': typeof AdminCadastrarRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/app/impacto': typeof AppImpactoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/resgates': typeof AppResgatesRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/cadastrar'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/admin/reservas'
    | '/app/impacto'
    | '/app/perfil'
    | '/app/resgates'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/cadastrar'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/admin/reservas'
    | '/app/impacto'
    | '/app/perfil'
    | '/app/resgates'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/cadastrar'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/admin/reservas'
    | '/app/impacto'
    | '/app/perfil'
    | '/app/resgates'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastrar': {
      id: '/admin/cadastrar'
      path: '/cadastrar'
      fullPath: '/admin/cadastrar'
      preLoaderRoute: typeof AdminCadastrarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/impacto': {
      id: '/app/impacto'
      path: '/impacto'
      fullPath: '/app/impacto'
      preLoaderRoute: typeof AppImpactoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resgates': {
      id: '/app/resgates'
      path: '/resgates'
      fullPath: '/app/resgates'
      preLoaderRoute: typeof AppResgatesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCadastrarRoute: typeof AdminCadastrarRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCadastrarRoute: AdminCadastrarRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppImpactoRoute: typeof AppImpactoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppResgatesRoute: typeof AppResgatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImpactoRoute: AppImpactoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppResgatesRoute: AppResgatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
